languageCode = "en-us"
languageName = "English (United-States)"
displayName = ":flag-us:"
isoCode = "en-US"
weight = 1
rtl = false

title = "About"
# logo = "img/logo.jpg"
# description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
# copyright = "&copy; 2022 Congo contributors"

dateFormat = "2 January 2006"

[author]
  name = "Remy Jaspers"
image = "img/author.jpg"
  headline = "Student Information Security Technology at TU Eindhoven"
bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { linkedin = "https://www.linkedin.com/in/remy-jaspers/" },
  ]
